#pragma once
/*
 * Auto-generated export forwarding header for version.dll
 * Generated by extract_exports.py
 * Inspired by Perfect DLL Proxy (https://github.com/mrexodia/perfect-dll-proxy)
 * 
 * Total Exports: 17
 * Original DLL Path: \\.\GLOBALROOT\SystemRoot\System32\version.dll
 * Architecture: x64 only
 * 
 * Usage:
 *   #include "exports/version.h"
 * 
 * This header uses MSVC #pragma directives to forward all exports
 * to the original system DLL without manual function implementation.
 * 
 * The GLOBALROOT path ensures compatibility regardless of Windows
 * installation directory and works at the NT kernel level.
 */

#ifndef VERSION_EXPORTS_H
#define VERSION_EXPORTS_H

// Export forwarding pragmas (x64 only)
// Format: #pragma comment(linker, "/EXPORT:FunctionName=Path.FunctionName,@Ordinal")

#pragma comment(linker, "/EXPORT:GetFileVersionInfoA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoA,@1")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoByHandle=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoByHandle,@2")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoExA,@3")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoExW,@4")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoSizeA,@5")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoSizeExA,@6")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoSizeExW,@7")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoSizeW,@8")
#pragma comment(linker, "/EXPORT:GetFileVersionInfoW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.GetFileVersionInfoW,@9")
#pragma comment(linker, "/EXPORT:VerFindFileA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerFindFileA,@10")
#pragma comment(linker, "/EXPORT:VerFindFileW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerFindFileW,@11")
#pragma comment(linker, "/EXPORT:VerInstallFileA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerInstallFileA,@12")
#pragma comment(linker, "/EXPORT:VerInstallFileW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerInstallFileW,@13")
#pragma comment(linker, "/EXPORT:VerLanguageNameA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerLanguageNameA,@14")
#pragma comment(linker, "/EXPORT:VerLanguageNameW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerLanguageNameW,@15")
#pragma comment(linker, "/EXPORT:VerQueryValueA=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerQueryValueA,@16")
#pragma comment(linker, "/EXPORT:VerQueryValueW=\\\\.\\GLOBALROOT\\SystemRoot\\System32\\version.dll.VerQueryValueW,@17")

#endif // VERSION_EXPORTS_H
